spring:
  datasource:
    dynamic:
      p6spy: true # 默认false,建议线上关闭。
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url:  jdbc:mysql://127.0.0.1:3306/low_code?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver

          # 3.2.0开始支持SPI可省略此配置
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.baomidou: debug
    com.hftech.meta: debug
server:
  port: 8081

mybatis-plus:
  # 扫描mapper.xml文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 扫描实体类
  typeAliasesPackage: com.example.entity
  # 主键类型
  global-config:
    #0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  #自定义SQL注入器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true